### ISSUE TITLE
Crash at isAnimatedGif

### ISSUE THREAD

**Issue by timrourke** [andismith/grunt-responsive-images#59]
Hi there! I'm having a strange problem with grunt crashing when it tries to run my responsive_images task. It seems to be missing some data that identifies the type of file being processed. I've never had a problem with this before, but I'm new to grunt, so this may very well be due to poor configuration of my tasks.

Below is my stack trace after running grunt --stack. If you have any insight or need additional info, let me know.

Thanks!

Running "responsive_images:myTask" (responsive_images) task
Fatal error: Cannot call method 'toUpperCase' of undefined
TypeError: Cannot call method 'toUpperCase' of undefined
    at isAnimatedGif (/Users/admin/Desktop/3dproof/node_modules/grunt-responsive-images/tasks/responsive_images.js:279:37)
    at gm.<anonymous> (/Users/admin/Desktop/3dproof/node_modules/grunt-responsive-images/tasks/responsive_images.js:314:12)
    at gm.EventEmitter.emit (events.js:106:17)
    at gm.<anonymous> (/Users/admin/Desktop/3dproof/node_modules/grunt-responsive-images/node_modules/gm/lib/getters.js:129:14)
    at ChildProcess.cb (/Users/admin/Desktop/3dproof/node_modules/grunt-responsive-images/node_modules/gm/lib/command.js:264:16)
    at ChildProcess.EventEmitter.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:805:12)
Tim:3dproof admin$ grunt

**Comment by andismith** [comment]
Fixed in 0.1.5
