### ISSUE TITLE
Cannot call method 'toUpperCase' of undefined

### ISSUE THREAD

**Issue by deanhume** [andismith/grunt-responsive-images#60]
If I add the following in my gruntfile:

	grunt.initConfig({
	  responsive_images: {
		myTask: {
		  options: {
			sizes: [{
			  width: 320,
			},{
			  width: 640,
			},{
			  width: 1024,
			}]
		  },
		  files: [{
			expand: true,
			src: ['**.{jpg,gif,png}'],
			cwd: 'images/',
			custom_dest: 'dest/{%= width %}/'
		  }]
		}
	  },
	})

I get the error **Cannot call method 'toUpperCase' of undefined**

This is the output:

*Running "responsive_images:myTask" (responsive_images) task
Fatal error: Cannot call method 'toUpperCase' of undefined
TypeError: Cannot call method 'toUpperCase' of undefined
    at isAnimatedGif (C:\Dev\picture\node_modules\grunt-responsive-images\tasks\
responsive_images.js:279:37)
    at gm.<anonymous> (C:\Dev\picture\node_modules\grunt-responsive-images\tasks
\responsive_images.js:314:12)
    at gm.EventEmitter.emit (events.js:106:17)
    at gm.<anonymous> (C:\Dev\picture\node_modules\grunt-responsive-images\node_
modules\gm\lib\getters.js:129:14)
    at ChildProcess.cb (C:\Dev\picture\node_modules\grunt-responsive-images\node
_modules\gm\lib\command.js:264:16)
    at ChildProcess.EventEmitter.emit (events.js:95:17)
    at Process.ChildProcess._handle.onexit (child_process.js:787:12)*

**Comment by andismith** [comment]
Fixed in 0.1.5
